### PR TITLE
[WIP] change blogs author

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
Do we want this to be changed?

### CODE REVIEW

**Comment by GerwinV** [comment]
I don't think you can change the author of a blog. It was written by Joke, not someone else.

**Comment by RonaldDijkstra** [comment]
Okay, in that case, shouldn't we have an 'archived' images folder?

**Comment by fatboypunk** [comment]
> I don't think you can change the author of a blog.

Of course you can.
`source/blog/nl/2016-11-08-met-defacto-aan-de-top-in-de-ad-ziekenhuis-top-100.markdown` I think this should be changed anyway so the author can change with it.

For the other blog it might be nice to leave her as the creator of the blog

**Comment by fatboypunk** [comment]
> Okay, in that case, shouldn't we have an 'archived' images folder?

We could we could also remove the missing icon image

**Comment by RonaldDijkstra** [comment]
Nice idea

**Comment by IwannaDJ** [comment]
I honestly think this should've never been a blog post. Maybe better to delete it or make a better story out of it? This is not blog worthy.

**Comment by RonaldDijkstra** [comment]
This is not the case of this PR, should've been an issue in the first place, sorry. I feel for Marcel's solution with the removal of the replacement image and for removing the post. Tomorrow I'll make this right.

**Comment by GerwinV** [comment]
Agree on that with @fatboypunk too.

**Pull request closed without merging**
