### PR TITLE
Minify HTML

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
Just a test. Settings are default. 

https://github.com/middleman/middleman-minify-html

### CODE REVIEW

**Comment by RonaldDijkstra** [comment]
| Page                   | N     | M     | Diff    |
|------------------------|-------|-------|---------|
| index.html             | 27 kb | 22 kb | - 18,5% |
| producten.html         | 21 kb | 17 kb | - 19,0% |
| zorg-dat-leren-...html | 31 kb | 25 kb | - 19,4% |

**Comment by RonaldDijkstra** [comment]
@sn3p difference is significant

**Comment by sn3p** [comment]
Alright! Lets give this a try then 👍 

But only on build I guess otherwise it's hard to debug.

**Comment by RonaldDijkstra** [comment]
It's only on build but I like to test some more.

**Pull request merged**
