### PR TITLE
Remove great David from website - but not before tomorrow

### PR DESCRIPTION
**Pull request by DavidFritsch**

### CODE REVIEW

**Comment by RonaldDijkstra** [comment]
NOT APPROVED.

**Comment by sn3p** [comment]
Awwww ironic last commit. Thanks David, all the best and may our paths cross again 👏

**Comment by sn3p** [comment]
Awwww ironic last commit. Thanks @DavidFritsch, all the best and may our paths cross again 👏

**Comment by RonaldDijkstra** [comment]
Agreed 👏

**Pull request merged**
