### PR TITLE
Add more options to conversion form CAPP Agile Learning

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
Extends the form with a number of options, so it gives our visitors more options than just requesting a demo. This is probably good for conversions, because a demo could be a little too much to convert for some visitors. And it makes it more clear for our sales dept what people actually want with filling the form. 

## Screenshots: 
screenshot_more_options

## Checked checkbox: 
checked

This works in IE9+

### CODE REVIEW

**Comment by fatboypunk** [comment]
What would this look like?

**Comment by fatboypunk** [comment]
> Hou me op de hoogte via e-mail

Are we actually planning to send emails about it? otherwise it might be wise to have another default

**Comment by RonaldDijkstra** [comment]
> Are we actually planning to send emails about it? otherwise it might be wise to have another default

I don't like checked by default checkboxes and removed it for now.

**Comment by RonaldDijkstra** [comment]
@fatboypunk screenshot in the PR now.

**Comment by fatboypunk** [comment]
@sn3p any thoughts on this?

**Comment by RonaldDijkstra** [comment]
I'll propose this tomorrow in a meeting. Most likely some tweaks coming ;-)

**Comment by fatboypunk** [comment]
> I'll propose this tomorrow in a meeting. Most likely some tweaks coming ;-)

Haha sure, i would like a default though maybe on more info. So that it doesn't add much of a barrier to the user.

**Comment by RonaldDijkstra** [comment]
You're right, probably the first one and maybe make clear all options could be checked

**Comment by RonaldDijkstra** [comment]
Removed the 'prijsopgave' option, now this is ready for review.

**Pull request merged**
