### PR TITLE
[READY] update e-learning starterkit content and hero

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
- [x] update German content 
- [x] update Dutch content
- [x] set hero background to be like product overview for e-learning starterkit

Assignment: 

- update content
- image in the hero (disapproved)

### CODE REVIEW

**Comment by dkhgh** [comment]
Screenshot?

**Comment by fatboypunk** [comment]
> Screenshot?

screen shot 2016-10-13 at 10 15 02

I don't like this tbh

**Comment by fatboypunk** [comment]
Can we minimalize the margin of the inner `<ul>`? and give the inner `<li>` a different symbol?
screen shot 2016-10-13 at 10 16 46

**Comment by sn3p** [comment]
Not sure either about the box, although it's way better then the black version from before.

**Comment by RonaldDijkstra** [comment]
Yup, back to the drawing table than.

**Comment by sn3p** [comment]
> Yup, back to the drawing table then.

Can do this together tomorrow if you want.

**Comment by RonaldDijkstra** [comment]
I want.

**Comment by dkhgh** [comment]
No box plz 😅

**Comment by RonaldDijkstra** [comment]
Alright 👍 I'll work on this one with @sn3p tomorrow

**Comment by fatboypunk** [comment]
If you remove the box, we can merge it now :)

**Comment by RonaldDijkstra** [comment]
Ugly cheap box is gone. Still not happy with the page as a whole, because there could be more done with this. But maybe that's the case for all pages?

**Pull request merged**
