### PR TITLE
Replace capp lms page 🇳🇱

### LINKED ISSUE #1243: Merge new and old capp lms page

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
This removes the old styling and page of CAPP on Defacto.nl, but keeps the pages online on Defactolearning.de and En.defacto.nl. It also adds new styling to navigation, solutions on the homepage and on product index.

- [x] Link hero to `/capp-lms`
- [x] Replace old CAPP LMS page with new one
- [x] Update CAPP LMS on Product index
- [x] Redirect old page to new one
- [x] Update Page title
- [x] Update solutions
- [x] Update CAPP LMS in Dropdown Navigation
- [x] Icons
- [x] Remove old screenshots

@lennartdefacto 

- [x] Update content on Solutions 
- [x] Update content on Product index 
- [x] Update content in Dropdown Navigation

Close #1243

### CODE REVIEW

**Comment by RonaldDijkstra** [comment]
```
- ./build/blog/zerocopter-veilige-software-door-ethical-hackers/index.html
  *  External link https://zerocopter.com/ failed: 525 No error
```

**Comment by RonaldDijkstra** [comment]
Deployed to https://staging.defacto.nl/

**Comment by RonaldDijkstra** [comment]
Time-out on external link in a blog post.

**Comment by sn3p** [comment]
screen shot 2018-07-30 at 12 52 22

Not sure about the 2 lines title. Maybe use `CAPP LMS` in the title and `Learning & Talent Management` in the description?

**Pull request merged**
