### PR TITLE
Add conversion page for e-book "Abenteuer Elearning"

### LINKED ISSUE #1879: conversion page e-book
Text: 
[title] E-Book: Abenteuer E-Learning
[subtitle] Laden Sie jetzt unser E-Book herunter und erhalten Sie Tipps und Tricks beim Einsatz von E-Learning.

Example form:
Screenshot 2019-05-21 at 11 52 38

Button: 
E-Book herunterladen

URL: 
/e-book-abenteuer-elearning

If they filled in info and click download, they get the e-book by email. Formkeep goes too k.walheim@defacto.nl and isabela@defacto.nl

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
- [x] Register page & path
- [x] Add header
- [x] Add form 

---

- [x] Fix email
  - [x] Content
  - [x] Setup

--- 

Close #1879

### CODE REVIEW

**Comment by RonaldDijkstra** [comment]
@isabelamy I wrote an email auto reply example for you, so you can easily translate it and make it your own.

```html
Hallo {{submission.name}},

Thanks for your download request of 'Abenteuer E-Learning', our E-Book about E-Learning. 

You can download your copy here now: 

[Download Your E-Book Here](https://www.defactolearning.de/pdf/Handbuch_Abenteuer_E-Learning.pdf) 

I hope you'll learn something from the insights we try to give with this book. 
And if you have any questions about the book, Defacto or our products, please ask. We're happy to help! 

Greetings, 

Isabela Wojtowicz<br>
Defacto Teamlead Deutschland<br>
[i.wojtowicz@defactolearning.de](mailto:i.wojtowicz@defactolearning.de)

```

**Comment by RonaldDijkstra** [comment]
Deploy preview URL: 

https://deploy-preview-1882--defacto-de.netlify.com/e-book-abenteuer-elearning

**Comment by isabelamy** [comment]
Subject: 
```html
E-Book 'Abenteuer E-Learning'
```

Content: 
```html
Hallo {{submission.name}},

Vielen Dank für das Herunterladen von 'Abenteuer E-Learning', das E-Book zum Thema E-Learning. 

Klicken Sie auf folgenden Link um es herunterzuladen: 

[Download Your E-Book Here](https://www.defactolearning.de/pdf/Handbuch_Abenteuer_E-Learning.pdf) 

Ich hoffe es hilft Ihnen weiter in ihrem eigenen E-Learning Abenteuer. Wenn Sie Fragen über E-Learning oder digitale Lernlösungen haben, helfen wir Ihnen gerne weiter!

Mit freundlichen Grüßen, 

Isabela Wojtowicz<br>
Country Manager Germany<br>
[i.wojtowicz@defactolearning.de](mailto:i.wojtowicz@defactolearning.de)

```

**Comment by RonaldDijkstra** [comment]
Thank you.

**Comment by RonaldDijkstra** [comment]
I talked to formkeep and indeed, no attachments for auto replies.

**Comment by RonaldDijkstra** [comment]
Deploy preview link: 

https://deploy-preview-1882--defacto-de.netlify.com/e-book-abenteuer-elearning

**Comment by RonaldDijkstra** [comment]
@isabelamy I've added the text to the mail and made a Bulletproof button for the download. 

https://buttons.cm/

I suggest you test the flow with the deploy preview link.

**Comment by EasterPeanut** [comment]
Nice, tested downloading it. 👍

Offtopic: @RonaldDijkstra do we support IE11 for our website?

**Comment by RonaldDijkstra** [comment]
Is there trouble in IE paradise?

**Pull request merged**
