### PR TITLE
Link rails vacancy

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
To it's own specific funnel in homerun.

### CODE REVIEW

**Comment by fatboypunk** [comment]
why?

**Comment by RonaldDijkstra** [comment]
I guess Esther cum suis want separate flows for every vacancy.

**Comment by fatboypunk** [comment]
> I guess Esther (c.s.) want separate flows for every vacancy.

Isn't frontend/backend enough? cc @tarzan @GerwinV

**Comment by RonaldDijkstra** [comment]
> @Esther·15:28
> ik wil graag weten voor welke vacature er gesolliciteerd wordt.

**Pull request closed without merging**
