### PR TITLE
[READY] Forms & productsheets

### PR DESCRIPTION
**Pull request by sn3p**
- [x] input type=email validation for IE9 and below.
- [x] download form plugin
- [x] CAPP productheets form
- [x] German CAPP productsheet (really old one)
- [x] Test in IE9

### CODE REVIEW

**Comment by sn3p** [comment]
It doesn't seem clear what's the actual German CAPP Leren productsheet. I added the [Dutch sheet](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/75656/577055/F718g7jOCG2EjxL/Productsheet_CAPP_Leren.pdf), but I don't think we have it in German. We have [this](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/75656/539214/pbVwfBd1OY7ndZJ/CAPP11-Eine-Plattform-fur-Ihre%20Personalentwicklung.pdf) sheet (CAPP11), but it's pretty old. Do we want people to download that?

**Comment by dkhgh** [comment]
Who can test this in IE so we can :shaved_ice:

**Comment by tarzan** [comment]
will do tomorrow!

**Comment by tarzan** [comment]
image

**Comment by tarzan** [comment]
image

**Comment by tarzan** [comment]
image
image

**Comment by sn3p** [comment]
@tarzan made a few adjustments, lets test monday?

**Comment by dkhgh** [comment]
@sn3p is this live on development?

**Comment by dkhgh** [comment]
Ok, @fatboypunk is testing on IE9 now

**Comment by sn3p** [comment]
Nice! It's not live yet, need to push it first.

**Comment by dkhgh** [comment]
Already did that. Valdation works but not all form submissions from ie9 end up ib formkeep :(

**Comment by sn3p** [comment]
Starting downloads from the thanks-you-page solves the IE9 download problem.
But it introduces a new problem... The download now gets blocked in Chrome and IE (haven't tested others). This is because the page is calling `window.open('download.pdf');` and this action didn't come form a [trusted event](http://www.w3.org/TR/DOM-Level-3-Events/#trusted-events). This worked before because the download was triggered but a user action.

screen shot 2015-09-30 at 17 48 32

**Comment by dkhgh** [comment]
Omg :(

**Comment by fatboypunk** [comment]
Can't we do something like `if ie9` :D



Met vriendelijke groet 

Marcel Horlings

**Comment by sn3p** [comment]
I think I see light at the end of the tunnel! brb

**Comment by sn3p** [comment]
Delaying the start of the download is not possible because it has to open before the form redirects to Formkeep. I did this when the download started from the thanks-page, but that's not the case anymore.

**Comment by dkhgh** [comment]
I meant when the popup shows

**Comment by sn3p** [comment]
@dkhgh @fatboypunk @tarzan does anyone want to test this before merging?
I've tested and seems ok, so don't mind merging myself. But maybe I've missed something..

**Comment by fatboypunk** [comment]
I'm ok with merge now and test tomorrow

**Comment by sn3p** [comment]
```
is geinteresseerd in CAPP: download productsheet
```

:(

**Comment by sn3p** [comment]
- [x] always validate in javascript regardless of the browser
- [x] post browser version to formkeep (for future debugging)

screen shot 2015-10-02 at 17 02 26

**Pull request merged**
