### PR TITLE
Add social proof section

### LINKED ISSUE #334: Use a "social proof" section on the Homepage
As suggested before 
- clients 
- users
- courses created
- courses passed

Or different stuff. Just not just show logos.

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
@lennartdefacto here's a draft for you to fiddle around with. The content I wrote isn't real. 

Based on old PR #381

Close #334

### CODE REVIEW

**Comment by RonaldDijkstra** [comment]
This is 'schaif' haha

**Comment by RonaldDijkstra** [comment]
Do you like to make it more like your own design concept?

**Comment by RonaldDijkstra** [comment]
Heard from @isabelamy she likes this one more without the description paragraphs.

**Comment by lennartdefacto** [comment]
screenshot social proof

**Comment by RonaldDijkstra** [comment]
Respons time is correct?

**Comment by fatboypunk** [comment]
> Respons time is correct?

For Capp and Agile they are, not sure about Capp11

**Pull request merged**
