### PR TITLE
[READY] Update homepage solutions with one extra CAPP page

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
This PR fixes the next things as based on the input by our German team as mentioned in #302: 

- changes the layout of solutions overview boxes to be more close to the top of the page on desktops and the responsive behavior of said boxes
- adds an extra box in the solutions overview boxes on the German website. CAPP differs now on the German website to Bilden and Entwickeln (not on defacto.nl so this needed to be localized)
- updates the content (including images) of the German pages about CAPP
- removes some unused stuff from styling (keywords part of solutions overview)
- updates the German /produkte page with one extra box (not on defacto.nl so this needed to be localized)
- updates the footer links to Bilden and Entwickeln on the German website
- redirects /capp-lms on the German website to /capp-bilden

### Homepage NL
homepage-nl

### Homepage DE
homepage-de

### CAPP Bilden
capp-bilden-page

### CAPP Entwickeln
capp-entwickeln-page

### CODE REVIEW

**Comment by isabelamy** [comment]
looking fabulous! :)

**Comment by fatboypunk** [comment]
I'll try to click through it at the end of the day, oke?

**Comment by RonaldDijkstra** [comment]
Thanks! 👍

**Comment by sn3p** [comment]
Nice @RonaldDijkstra 💯

**Comment by RonaldDijkstra** [comment]
Thanks @sn3p !

**Pull request merged**
