### PR TITLE
Update general blog style

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
- [ ] Add header images to blog post layout

## Todo: 
WVTTK

## Screenshots:

leren is werken werken is leren defacto

### CODE REVIEW

**Comment by sn3p** [comment]
What about dynamically resizing the `featured_image`?
I found [this Middleman issue](https://github.com/kubenstein/middleman-simple-thumbnailer) and [this gem](https://github.com/kubenstein/middleman-simple-thumbnailer) that might do the job.

With this gem we could prolly do something like this? (**untested**)

```rb
def blog_thumb(article = current_article)
  if article.data.featured_thumb.present? do
    image_path article.data.featured_thumb
  elsif article.data.featured_image.present? do
    image_path article.data.featured_image, resize_to: 640
  else
    image_path "blog-featured-thumb.jpg"
  end
end
```

```erb
<%= image_tag(blog_thumb(article), alt: article.title) %>
```

**Comment by RonaldDijkstra** [comment]
Which issue?

**Comment by RonaldDijkstra** [comment]
Testing here #476

**Comment by sn3p** [comment]
> Which issue?

Updated the link

**Pull request closed without merging**
