### PR TITLE
[READY] Hound settings

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
I'd like to make some changes to Hound settings, like the depths of nesting and selector depths. I made 2 commits, one with the default settings and one with changes. 

I have a few questions about the settings LS uses, becasue they differ from the default: 

LS: 
```
 ExtendDirective:
  enabled: true

QualifyingElement:
  enabled: true
  allow_element_with_attribute: true
  allow_element_with_class: true
  allow_element_with_id: false

SelectorFormat:
  enabled: true
  convention: hyphenated_BEM

SpaceAfterVariableColon:
  enabled: false
  style: one_space 
```

Default:
```
ExtendDirective:
  enabled: false

QualifyingElement:
  enabled: true
  allow_element_with_attribute: false
  allow_element_with_class: false
  allow_element_with_id: false

SelectorFormat:
  enabled: true
  convention: hyphenated_lowercase

SpaceAfterVariableColon:
  enabled: true
  style: one_space
```
Would like to talk tomorrow about these in a spare moment, because I'd want to know where they are for. @fatboypunk or @sn3p

### CODE REVIEW

**Comment by fatboypunk** [comment]
https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md
As a reference

**Comment by RonaldDijkstra** [comment]
Thanks for that, maybe that's enough

**Comment by RonaldDijkstra** [comment]
Is enough to understand what every rule is for. 

1. This website doesn't use @extend, LS landing does so this could be true 
2. QualifyingElement should be true for classes, because we use `body.classname` like `body.bedankt` from now on
3. I can understand why you use **Hyphenated_BEM** because LS is a big project, but I guess the website doesn't need this, so hyphenated_lowercase should be it
4. And SpaceAfterVariableColon I think must be true for the website

**Comment by sn3p** [comment]
> 1. This website doesn't use **@extend**, LS landing does so this could be true
2. **QualifyingElement** should be true for classes, because we use `body.classname` like `body.bedankt` from now on
3. I can understand why you use **Hyphenated_BEM** because LS is a big project, but I guess the website doesn't need this, so hyphenated_lowercase should be it
4. And **SpaceAfterVariableColon** I think must be true for the website

Nice @RonaldDijkstra 

1. Don't we use `@extend` for bourbon mixins?
2. Yep, bad practice in general but for us body classes is an exception imo.
3. I prefer `hyphenated_lowercase` but Middleman/rails generated `snake_case` classes. In LS we have **SelectorFormat** disabled for this same reason, so I'd do the same for the website.
4. Enable **SpaceAfterVariableColon** with style: `at_least_one_space`.

**Comment by RonaldDijkstra** [comment]
> 1. Don't we use @extend for bourbon mixins?

AFAIK not: 

```
Searching 42 files for "@extend"

0 matches across 0 files
```

**Comment by sn3p** [comment]
Ah doh, I confused `@extend` with `@include`.

**Comment by RonaldDijkstra** [comment]
Thanks @sn3p

**Pull request merged**
