### PR TITLE
Add Client Cases

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
This is a (visual) concept for an 'extended' portfolio, as briefly mentioned in issue #331.

The content is all completely fake at this time, a video in the content is just an example how that would look and is for sure not a necessity. 

-  ~~Concepting (cases should not only be at the homepage, for example)~~
- [ ] Content Dutch cases
- ~~Content German cases (eventually)~~

## Homepage
homepage-cases

## Case 
case-concept

### CODE REVIEW

**Comment by fatboypunk** [comment]
> Content German cases (eventually)

So we could do this in a seperate PR?

**Comment by fatboypunk** [comment]
> Concepting (cases should not only be at the homepage, for example)

For now (this PR) this is good enough?

**Comment by RonaldDijkstra** [comment]
For me it's a starting point to talk about how we could do this client cases. 

German is eventually for now for me because they have less time to create content.

**Comment by fatboypunk** [comment]
> For me it's a starting point to talk about how we could do these client cases.

we could do that in the issue, I'd like to have this PR as small as possible because i like it and therefore we can push it sooner

**Comment by RonaldDijkstra** [comment]
That's smart thinking.

**Comment by RonaldDijkstra** [comment]
Maybe someday

**Pull request closed without merging**
