### PR TITLE
[READY] Deploy locale to different domain

### PR DESCRIPTION
**Pull request by sn3p**
fixes https://github.com/DefactoSoftware/website/issues/189, fixes https://github.com/DefactoSoftware/website/issues/144

### Todo
- [x] Rake tasks for building and deploying
- [x] Dynamic CNAME per locale
- [x] Fix `page_classes` helper
- [x] Fix language selection
- [x] Update README.md
- [x] Fix sitemap.xml and robots.txt
- [x] Setup redirects (from `/de/*` to `http://defactolearning.de/*`)
- [x] Setup CNAMES
- [x] Setup DNS records

--

### Links
**NL**
- https://github.com/DefactoSoftware/website-nl
- http://defactosoftware.github.io/website-nl
- http://tempnl.defacto.nl

**DE**
- https://github.com/DefactoSoftware/website-de
- http://defactosoftware.github.io/website-de
- http://tempde.defacto.nl

--

Serving, building and deploying now works through rake tasks:

##### Serve
```bash
rake serve:nl
rake serve:de
```

##### Build
```bash
rake build:nl
rake build:de
```

##### Deploy (and build before)
```bash
rake deploy:nl
rake deploy:de
rake deploy # Deploy all locales
```

`:nl` is deployed to [website/tree/gh-pages](https://github.com/DefactoSoftware/website/tree/gh-pages). `:de` is deployed to [website-de/tree/gh-pages](https://github.com/DefactoSoftware/website-de/tree/gh-pages).

### CODE REVIEW

**Comment by sn3p** [comment]
@RonaldDijkstra I think we are almost ready to go.

Can you help test and see if everything works?
Temporary URLs are [tempnl.defacto.nl](http://tempnl.defacto.nl) and [tempde.defacto.nl](http://tempde.defacto.nl). Language selector should works as well, so this enables you to switch between domains.

**Note:** if you want to serve, build or deploy this branch, the commands have changed (using rake tasks now).

**Comment by RonaldDijkstra** [comment]
I tested the tempde and tempnl domains with [Screaming Frog](https://www.screamingfrog.co.uk/seo-spider/)

**tempnl** seems all good

**tempde** 

- http://tempde.defacto.nl/elearning/ below subheading about starterkit a 404 link because use of /de/ 
- On the homepage (Was unsere kunden sagen box) the links to testimonials seem broken (testimonials.html#id)

**Comment by sn3p** [comment]
Right now `build/de*` is removed after building the `nl` site. So if we want to keep these urls accessible we need redirects.

Can we do redirects through DNS config?

Or do something like this?

```rb
require "rack/rewrite"

use Rack::Rewrite do
  r301 %r{/de/(.*)\.html}, "http://www.defactolearning.de/$1"
end
```

Not sure if this is working, but as a last resort:

```rb
redirect "/de/index.html", to: "http://www.defactolearning.de"
redirect "/de/kontakt.html", to: "http://www.defactolearning.de/kontakt"
```

@tarzan your thoughts?

**Comment by sn3p** [comment]
@RonaldDijkstra redirects are done, can you do another check?

**Comment by RonaldDijkstra** [comment]
##### Works

- All redirects work (tempnl.defacto.nl/de to tempde.defacto.nl etc)! 
- The 404 return code seems fixed in this new build (#143)! Aight

##### Problems/issues

- It seems some DE pages do not load the corresponding css files: 

http://tempde.defacto.nl/produkte/ 
http://tempde.defacto.nl/qualitatspass/ 
http://tempde.defacto.nl/360-feedback/ (watching this a bit longer I guess it's a general bug because of the number as a start in the CSS file, see the actual live page on http://www.defacto.nl/360-feedback/ and the hero header there)
http://tempde.defacto.nl/service/ 
http://tempde.defacto.nl/referenzen/ 

- There's a link to tempde.defacto.nl/blog in the sitemap.xml and the page exists now http://tempde.defacto.nl/blog/ (posts do work to on DE URL's)
It does not load corresponsing css and is not mentioned in the main nav on the German website. 
Could we do this later on and close the page for now? 
Or fix it and ask the germans to come up with a post? Let me know!  

- The Google Analytics code is correct because we could segment this on hostname and make seperate views, but we still need autolinker for that. We need this on jobs.defacto.nl, www.defacto.nl and www.defactolearning.de, [following the single snippet on multiple domains paragraph](https://developers.google.com/analytics/devguides/collection/analyticsjs/linker#using_a_single_snippet_on_all_domains) it must be like this:

 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-6700447-1', 'auto', {'allowLinker': true});
  ga('require', 'linkid');
  ga('require', 'linker');
  ga('linker:autoLink', ['www.defacto.nl', 'jobs.defacto.nl', 'www.defactolearning.de']);
  ga('send', 'pageview');
</script>

##### Non-technical stuff, but still needs to be done when going live with new domain

- The AdWords campaign for Germany needs changes (I pause it, we deploy the site, I change the URL's in the ads and make it live again)

**Comment by sn3p** [comment]
@RonaldDijkstra thanks, awesome testing 💯

- Fixed the styling issues (`page_classes` helper was broken)
- Blog is ignored while building `:de` (also in sitemap.xml)
- Updated GA tracking snippet, including the `track_conversion` exception (guess we still need that?):

```erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-6700447-1', 'auto', {'allowLinker': true});
  ga('require', 'linkid');
  ga('require', 'linker');
  ga('linker:autoLink', ['www.defacto.nl', 'jobs.defacto.nl', 'www.defactolearning.de']);
  <% if current_page.data.track_conversion %>
    var regex = new RegExp("[\\?&]form=([^&#]*)");
    var results = regex.exec(location.search);
    var form = results === null ? '' : results[1].toLowerCase();
    ga('send', 'pageview', '/bedankt/' + form);
  <% else %>
    ga('send', 'pageview');
  <% end %>
</script>
```

Deployed again on the temp urls like before.

**Comment by dkhgh** [comment]
I think css classes & id's can't start with a number, so that body class for 360 is probably f*****d

**Comment by sn3p** [comment]
page_classes starting with numbers are prefixed: `x360-feedback` :p

I think in HTML5 classes an ids starting with numbers is now allowed, but CSS can't target them unless the leading number is escaped: `.\360-feedback`

**Comment by RonaldDijkstra** [comment]
Thanks @sn3p for all the work. 

- Yes, we still need the conversion tracking on the thank you page, because we track which conversion is what from the virtual pageview /bedankt/ + form
- The issue with the css of the 360-feedback page is something for another issue, isn't it?

I think we're ready for deploying to defactolearning.de. Yesterday I made the Google Analytics views ready as far as I could.

**Comment by sn3p** [comment]
> The issue with the css of the 360-feedback page is something for another issue, isn't it?
I don't see issues with this page and can't find a class in the CSS that starts with a digit.

**Comment by RonaldDijkstra** [comment]
@sn3p yep, you're right, so nevermind :+1:

**Comment by sn3p** [comment]
Then we're good to go. Just need to update the [CNAME](https://github.com/DefactoSoftware/website/blob/matthijs/deploy-each-locale/source/CNAME.erb) urls and update the DNS records.

**Comment by RonaldDijkstra** [comment]
I just tested the redirects again. On the http://tempnl.defacto.nl/de URL's the redirects seem not to work. 
I checked the branch out and locally it works just fine. Am I missing something here @sn3p?

**Comment by sn3p** [comment]
@RonaldDijkstra my bad, should be good now!

**Comment by RonaldDijkstra** [comment]
It is, nice!

Op 3 mei 2016 om 19:03 heeft Matthijs Kuiper <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@RonaldDijkstra<https://github.com/RonaldDijkstra> my bad, should be good now!

-

**Comment by RonaldDijkstra** [comment]
It seems we have some small troubles with the 404's now on both 
http://tempnl.defacto.nl and http://tempde.defacto.nl 

**Expected:** 
- graphic and text centered
- menu (header and footer) to link to correct URL's on whatever URL you are

See: http://www.defacto.nl/test and for sub/sub dirs dirs http://www.defacto.nl/test/test

**Output:**
- graphic and text left aligned
- menu links to incorrect URL's on sub/sub dirs http://tempnl.defacto.nl/test/test (maybe it's me who's missing something here @sn3p? This is a kind of an edge case because we do not use sub/sub dirs, but it's still possible to do as own input by the user)

**Comment by sn3p** [comment]
@RonaldDijkstra nice find, fixed now (see [tempnl.defacto.nl](http://tempnl.defacto.nl) and [tempde.defacto.nl](http://tempde.defacto.nl)).
The `defactolearning.de` is currently being transferred to TransIP. After that we're ready to go.

**Comment by fatboypunk** [comment]
> It seems we have some small troubles with the 404's now on both

is this issue resolved or is there an issue made for this?

**Comment by RonaldDijkstra** [comment]
Yes @sn3p did, see last commit

**Pull request merged**
