### PR TITLE
Add Proof section

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
Issue #334 

- [ ] Concepting, how many items? Etc. 
- [ ] Dutch Content
- [ ] German Content 

### 2 concepts

proof

metrics-social-proof

### CODE REVIEW

**Comment by AnneNH** [comment]
the second one

**Comment by fatboypunk** [comment]
First one please it's more direct and gives a more direct sense of how much it is.
Maybe remove the `55 klanten`? doesn't seem as much like this not sure about the `klanttevredenheid`

**Comment by RonaldDijkstra** [comment]
Thanks for your input

**Comment by sn3p** [comment]
Nice, I love stats!

I prefer full numbers (first example). They are easier to read, but I'd try to evenly distribute (visually) the large numbers over the columns, e.g. in the middle or on the outsides.
The second example looks a bit more balanced, 3 columns is less cluttered.

I agree with fatboypunk that the amount of customers doesn't really add anything.
Lets figure out what data is interesting to communicate. Different data asks for a different presentation (form follows data).

What place you think we should show these stats on the website? Lets mock this into a screenshot :)

**Comment by RonaldDijkstra** [comment]
Thank you!

**Comment by RonaldDijkstra** [comment]
> What place you think we should show these stats on the website? Lets mock this into a screenshot :)

#### Just right above the logos of clients



#### Or after the solution boxes



I make sure I'll use real data soon.

**Comment by GlennGeelen** [comment]
With the first image it feels more like you want to display defacto overall stats. 

With the second image I think it have to be relevant stats for the columns that are above them, else it might be confusing for the users.

So I think it depends on what stats you want to show, where to position the stats on the site.

**Comment by sn3p** [comment]
Agree, what @GlennGeelen said :)

**Comment by fatboypunk** [comment]
Jup, still like the first one though! 💃

**Comment by RonaldDijkstra** [comment]
Maybe someday

**Pull request closed without merging**
