### PR TITLE
Merge hosting & security into 1 file

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
Merge into 1 file for better maintenance.
Alphabetise the paths list in de.yml
Remove not longer needed redirects.

### CODE REVIEW

**Comment by fatboypunk** [comment]
there's only stuff removed?

**Comment by RonaldDijkstra** [comment]
only useless stuff, like 3 of the same frame pages for every locale. Maybe merge is a wrong word here? Or did I make a mistake? 

And ordered the paths in de.yml alphabetical because it annoyed me

**Comment by fatboypunk** [comment]
> Maybe merge is a wrong word here?

yeah was confused by this

**Comment by RonaldDijkstra** [comment]
I’ll update the commit message for better history then.

**Pull request merged**
