### PR TITLE
Add links to product pages

### LINKED ISSUE #1757: Product Pages link sections at bottom
The last part on the german product pages is missing. Just as on the Gesundheitswesen page (https://www.defactolearning.de/gesundheitswesen/), there should be a referral to our other product pages. With the following text (except of the page that you are currently on):

[title] Weitere Anwendungen von CAPP:
Learning Management (https://www.defactolearning.de/capp-learning-management/)
Talent Management (https://www.defactolearning.de/capp-talent-management/)
Compliance & Qualifikationsmanagement  (https://www.defactolearning.de/capp-compliance-qualifikationsmanagement/)
Agile Learning (https://www.defactolearning.de/capp-agile-learning/)

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
Close #1757

### CODE REVIEW

**Comment by michellusthof** [comment]
@RonaldDijkstra Should it say 'Erleben Sie CAPP Learning Management live!' on every product page? I would expect a specific CTA text for each product page referring to the page you're on?

**Comment by RonaldDijkstra** [comment]
I didn't change that here, so please make an issue for it. 👍

**Comment by michellusthof** [comment]
> I didn't change that here, so please make an issue for it. 👍

Will do. Other then that I have no remarks, so approved.

**Comment by RonaldDijkstra** [comment]
Cool thx

**Pull request merged**
