### PR TITLE
[READY] Center blog posts again

### PR DESCRIPTION
**Pull request by RonaldDijkstra**

### CODE REVIEW

**Comment by RonaldDijkstra** [comment]
The blog posts went far to the left 

With this: 

`body[class^="blog_"],
body[class*="_index"]`

The `.post-body` on the blog post got targeted. AFAIK we don't need this class on the blog post layout, as can be seen on the screenshot below: 
bevoegd is niet bekwaam waar bekwaamheid echt over gaat defacto

**Comment by fatboypunk** [comment]
Wouldn't it be better to change the css blocks so bot are needed before it get's executed not just one?

**Comment by fatboypunk** [comment]
I think just dropping the comma would be enough

**Comment by RonaldDijkstra** [comment]
Then we're losing some ofthe style on the indexes. 

blog2 defacto

**Pull request merged**
